### ISSUE TITLE
git clean -Xf is a big productivity loss for me

### ISSUE THREAD

**Issue by satnam6502** [project-oak/silveroak#505] opened 2021-02-02 21:27 UTC
I keep getting stung by the `git clean -Xfd` command in our Makefiles. I've lost about half an hours work writing a tcl script to drive FPGA implementation for the AES block because I forgot to add this tcl script to the `.gitignore`.

I think we should reconsider a scheme that is so brutal about deleting files and that requires us to explicitly whitelist files before typing `make` otherwise they get deleted.

**Comment by blaxill** [comment] 2021-02-03 00:37
I'd like to have generated files in specific directories, that way we could nuke only those directories and know everything else should be kept. I think for the Coq extraction this means having an extraction directory. 

Happy for any other fix in the meantime.

**Comment by jadephilipoom** [comment] 2021-02-03 09:40
We can take care of Coq build artifacts like `.vo` files by using `make -f Makefile.coq clean`. Doing that plus a directory for extraction files sounds like a good solution to me!

**Comment by jadephilipoom** [comment] 2021-08-23 08:45
We now use `make -f Makefile.coq clean`, so I think the problem is fixed; closing this issue.

**Closed by jadephilipoom** 2021-08-23 08:45 UTC
Labels: P2, P3, friction
